name: parkking
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl_phone_field: ^3.2.0
  firebase_core: ^3.11.0
  flutter_svg: ^2.0.17
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  url_launcher: ^6.2.4
  cloud_firestore_web: ^4.4.2
  cloud_firestore: ^5.6.2
  firebase_core_web: ^2.19.0
  dart_geohash: ^2.1.0
  firebase_database: ^11.3.2
  google_places_flutter: ^2.0.9
  firebase_auth: ^5.4.2
  firebase_storage: ^12.4.2
  smooth_page_indicator: ^1.2.0+3
  google_maps_flutter: ^2.5.0
  google_maps_flutter_platform_interface: ^2.4.0
  http: ^1.2.2
  geocoding: ^3.0.0


dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0  # Atualizar para a versão mais recente

flutter_test:
  sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"  # Caminho para o seu ícone

flutter:
  uses-material-design: true
  assets:
    - assets/images/Welcome.png
    - assets/images/Easy.png
    - assets/images/Security.png
    - assets/icones/google_logo.svg
